### ISSUE TITLE
Attributes written as arrays of size 1

### ISSUE THREAD

**Issue by rayosborn** [nexpy/nexusformat#32]
If an attribute is written as an array of size 1, it is not correctly read in as a scalar value. 

In a file supplied by Steve Collins (Diamond Light Source), the target attribute of a linked object was written this way.

    >>> diamond_file.nxfile['/entry1/instrument/ic1monitor/ic1monitor'].attrs['target']
    array([b'/entry1/instrument/ic1monitor/ic1monitor'], 
          dtype='|S41')
    >>> diamond_file.nxfile['/entry1/instrument/ic1monitor/ic1monitor'].attrs['target'].shape
    (1,)

The fix is to make sure that all size 1 arrays are converted to scalars when they are read.

    >>> np.asscalar(diamond_file.nxfile['/entry1/default/ic1monitor'].attrs['target'])
    b'/entry1/instrument/ic1monitor/ic1monitor'

**Comment by cpascual** [comment]
What about size 1 arrays that are *intended* to be arrays?
Is there some way to identify them in the nexus standard and spare them this treatment?

I am thinking, e.g. on a NXscan where the scan just happens to have 1 point...
IMHO it is not ok to read it as a scalar...

**Comment by vasole** [comment]
Perhaps you are discussing other thing, but as far as I have understood the recommendation is to avoid the use of arrays as attributes. So, it does not shock me that something that tries to write NeXus files and receives a string array as attribute attempts to convert it to a string or raise an exception.

**Comment by cpascual** [comment]
Ooops!, right... I was thinking of datasets, not attributes. My bad.
So, if this issue applies only to attributes, I withdraw what I said

> as far as I have understood the recommendation is to avoid the use of arrays as attributes

I think you are right.. at least that is what I interpret from [here](https://support.hdfgroup.org/HDF5/doc1.6/UG/13_Attributes.html)
